name: Feature Request
description: Request something new to be added to Nebula
title: "[Feature Request]: "
labels: [":hammer: Feature Request"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature you'd like
      description: Provide a clear description of the feature you'd like implemented in Nebula
    validations:
      required: true
  - type: textarea
    id: benefits
    attributes:
      label: Describe the benefits this feature would bring to Nebula users
      description: Explain the measurable benefits this feature would achieve for existing Nebula users
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
